architect:
- yegor256
- yegor256
- davvd
install: |
  sudo pecl install xdebug
  echo "zend_extension=xdebug.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
  composer install
merge:
  script: |
    ./vendor/phing/phing/bin/phing
deploy:
  script: |
    ./vendor/phing/phing/bin/phing
release:
  script: |
    ./vendor/phing/phing/bin/phing
