architect:
- davvd
- yegor256
install: |
  sudo pecl install xdebug
  echo "zend_extension=xdebug.so" > xdebug.ini
  sudo mv xdebug.ini /etc/php5/cli/conf.d
  composer install
  sudo npm install jscoverage -g
merge:
  script: |
    ./vendor/phing/phing/bin/phing
  commanders:
  - yegor256
deploy:
  script: |
    ./vendor/phing/phing/bin/phing
release:
  script: ./vendor/phing/phing/bin/phing