language: php
install:
  - pecl install xdebug
  - echo "zend_extension=xdebug.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
  - composer install
script:
  - ./vendor/phing/phing/bin/phing
